import React, { useState } from 'react';
import { X, Settings, Download, FileJson, FileText, Smartphone, Cpu, Save } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import clsx from 'clsx';
import { useStore } from '../../store/useStore';

export function SettingsModal({ onClose }) {
  const [activeTab, setActiveTab] = useState('data'); // 'visual' | 'ai' | 'data'
  const { nodes, projects, activeProjectId } = useStore();

  const activeProjectTitle = projects.find(p => p.id === activeProjectId)?.title || "Untitled Universe";

  const handleExportJSON = () => {
    if (!nodes || nodes.length === 0) return;

    const dataStr = JSON.stringify({ project: activeProjectTitle, nodes }, null, 2);
    const blob = new Blob([dataStr], { type: "application/json" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = `Sidera_${activeProjectTitle.replace(/\s+/g, '_')}_${Date.now()}.json`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleExportMarkdown = () => {
    if (!nodes || nodes.length === 0) return;

    let mdContent = `# ${activeProjectTitle}\n\nGenerated by Sidera AI Starmap\n\n---\n\n`;

    nodes.forEach((node, index) => {
      mdContent += `## ${index + 1}. ${node.question}\n\n`;
      mdContent += `**Sidera:** ${node.answer}\n\n`;
      if (node.keywords && node.keywords.length > 0) {
        mdContent += `> Keywords: ${node.keywords.join(', ')}\n\n`;
      }
      mdContent += `---\n\n`;
    });

    const blob = new Blob([mdContent], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement('a');
    link.href = url;
    link.download = `Sidera_Starmap_${activeProjectTitle.replace(/\s+/g, '_')}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const tabs = [
    { id: 'data', label: 'Data Management', icon: Save },
    { id: 'visual', label: 'Ship Controls', icon: Smartphone },
    { id: 'ai', label: 'Intelligence', icon: Cpu },
  ];

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      {/* Modal Container */}
      <motion.div
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.95 }}
        className="w-full max-w-2xl glass-panel rounded-2xl overflow-hidden flex flex-col max-h-[85vh]"
      >
        {/* Header */}
        <div className="flex items-center justify-between p-6 border-b border-white/10 bg-white/5">
          <div className="flex items-center gap-3">
            <div className="p-2 rounded-lg bg-accent/20 text-accent">
              <Settings size={24} />
            </div>
            <div>
              <h2 className="text-xl font-bold text-white tracking-wide">Ship Settings</h2>
              <p className="text-sm text-gray-400">Configure your exploration vessel</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-full hover:bg-white/10 text-gray-400 hover:text-white transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Tabs */}
        <div className="flex border-b border-white/10 px-6 pt-4 gap-6">
          {tabs.map(tab => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={clsx(
                "pb-3 text-sm font-medium flex items-center gap-2 transition-all relative",
                activeTab === tab.id ? "text-accent" : "text-gray-500 hover:text-gray-300"
              )}
            >
              <tab.icon size={16} />
              {tab.label}
              {activeTab === tab.id && (
                <motion.div
                  layoutId="activeTabSettings"
                  className="absolute bottom-0 left-0 right-0 h-0.5 bg-accent shadow-[0_0_10px_var(--color-accent)]"
                />
              )}
            </button>
          ))}
        </div>

        {/* Content */}
        <div className="p-8 overflow-y-auto custom-scrollbar">
          <AnimatePresence mode="wait">

            {activeTab === 'data' && (
              <motion.div
                key="data"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-8"
              >
                <Section title="Export Starmap" icon={Download}>
                  <p className="text-sm text-gray-400 mb-4">
                    Download your current exploration data for safekeeping or sharing.
                  </p>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <button
                      onClick={handleExportJSON}
                      className="flex flex-col items-center gap-3 p-6 rounded-xl bg-white/5 border border-white/10 hover:border-accent/50 hover:bg-accent/5 transition-all group"
                    >
                      <FileJson size={32} className="text-gray-500 group-hover:text-accent transition-colors" />
                      <div className="text-center">
                        <h4 className="font-bold text-white">Export as JSON</h4>
                        <p className="text-xs text-gray-500 mt-1">Full data backup including coordinates</p>
                      </div>
                    </button>

                    <button
                      onClick={handleExportMarkdown}
                      className="flex flex-col items-center gap-3 p-6 rounded-xl bg-white/5 border border-white/10 hover:border-accent/50 hover:bg-accent/5 transition-all group"
                    >
                      <FileText size={32} className="text-gray-500 group-hover:text-accent transition-colors" />
                      <div className="text-center">
                        <h4 className="font-bold text-white">Export as Markdown</h4>
                        <p className="text-xs text-gray-500 mt-1">Readable document format for notes</p>
                      </div>
                    </button>
                  </div>
                </Section>
              </motion.div>
            )}

            {activeTab === 'visual' && (
              <motion.div
                key="visual"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-6 flex flex-col items-center justify-center py-10 opacity-50"
              >
                <Smartphone size={48} className="text-gray-600 mb-4" />
                <p className="text-gray-400 font-medium">Visual Controls Offline</p>
                <p className="text-xs text-gray-600">Graphics settings will be available in the next update.</p>
              </motion.div>
            )}

            {activeTab === 'ai' && (
              <motion.div
                key="ai"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                className="space-y-6 flex flex-col items-center justify-center py-10 opacity-50"
              >
                <Cpu size={48} className="text-gray-600 mb-4" />
                <p className="text-gray-400 font-medium">AI Core Calibrating</p>
                <p className="text-xs text-gray-600">Model parameters are locked by the administrator.</p>
              </motion.div>
            )}

          </AnimatePresence>
        </div>
      </motion.div>
    </div>
  );
}

// Reuseable Components
function Section({ title, icon: Icon, children }) {
  return (
    <div className="space-y-4">
      <h3 className="text-sm font-bold text-gray-400 uppercase tracking-widest flex items-center gap-2">
        <Icon size={16} /> {title}
      </h3>
      {children}
    </div>
  )
}
